from typing import List, Dict, Any
import io
from datetime import datetime
import xlsxwriter
from django.http import HttpResponse
from django.utils.translation import gettext as _

from .report_generator import ReportGenerator


class ExcelReportGenerator(ReportGenerator):
    
    
    def get_content_type(self) -> str:
        return 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    
    def get_file_extension(self) -> str:
        return 'xlsx'
    
    def generate_product_report(self, products: List[Dict[str, Any]], title: str = "Product Report") -> HttpResponse:
        
        buffer = io.BytesIO()
        
        workbook = xlsxwriter.Workbook(buffer)
        worksheet = workbook.add_worksheet(_("Products"))
        
        
        header_format = workbook.add_format({
            'bold': True,
            'bg_color': '#4F81BD',
            'color': 'white',
            'align': 'center',
            'valign': 'vcenter',
            'border': 1,
            'font_size': 12
        })
        
        title_format = workbook.add_format({
            'bold': True,
            'color': '#1F497D',
            'align': 'center',
            'valign': 'vcenter',
            'font_size': 16,
            'border': 0
        })
        
        date_format = workbook.add_format({
            'color': '#666666',
            'align': 'center',
            'font_size': 10,
            'italic': True
        })
        
        row_format_even = workbook.add_format({
            'bg_color': '#DCE6F1',
            'border': 1,
            'align': 'left',
            'valign': 'vcenter'
        })
        
        row_format_odd = workbook.add_format({
            'bg_color': '#FFFFFF',
            'border': 1,
            'align': 'left',
            'valign': 'vcenter'
        })
        
        number_format = workbook.add_format({
            'border': 1,
            'align': 'right',
            'valign': 'vcenter',
            'num_format': '#,##0'
        })
        
        number_format_usd = workbook.add_format({
            'border': 1,
            'align': 'right',
            'valign': 'vcenter',
            'num_format': '$#,##0.00'
        })
        
        footer_format = workbook.add_format({
            'color': '#666666',
            'italic': True,
            'font_size': 10
        })
        
        
        worksheet.set_column('A:A', 15)  
        worksheet.set_column('B:B', 30)  
        worksheet.set_column('C:C', 50)  
        worksheet.set_column('D:D', 20)  
        worksheet.set_column('E:E', 20)  
        
        worksheet.merge_range('A1:E1', title, title_format)
        current_datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        worksheet.merge_range('A2:E2', _("Generated on: ") + current_datetime, date_format)
        
        headers = [
            _("Reference"), 
            _("Title"), 
            _("Description"), 
            _("Price (COP)"),
            _("Price (USD)")
        ]
        for col, header in enumerate(headers):
            worksheet.write(3, col, header, header_format)
        
        for i, product in enumerate(products):
            row = i + 4  
            row_format = row_format_even if i % 2 == 0 else row_format_odd
            
            worksheet.write(row, 0, product.get('reference', ''), row_format)
            worksheet.write(row, 1, product.get('title', ''), row_format)
            description = product.get('description', '')
            if len(description) > 100:
                description = description[:100] + '...'
            worksheet.write(row, 2, description, row_format)
            worksheet.write(row, 3, product.get('price', 0), number_format)
            worksheet.write(row, 4, product.get('price_dolar', 0), number_format_usd)
        
        footer_row = len(products) + 5
        footer_text = _("This report is automatically generated by NEXO E-commerce system.")
        worksheet.merge_range(f'A{footer_row}:E{footer_row}', footer_text, footer_format)
        
        chart = workbook.add_chart({'type': 'column'})
        
        
        chart.add_series({
            'name': _('Price (USD)'),
            'categories': [_('Products'), 4, 0, 3 + len(products), 0], 
            'values': [_('Products'), 4, 4, 3 + len(products), 4],  
            'fill': {'color': '#4F81BD'},
            'data_labels': {'value': True}
        })
        
        chart.set_title({'name': _('Product Prices Comparison')})
        chart.set_x_axis({'name': _('Products')})
        chart.set_y_axis({'name': _('Price (USD)')})
        chart.set_style(10)  
        
        chart_row = len(products) + 7
        worksheet.insert_chart(f'A{chart_row}', chart, {'x_scale': 1.5, 'y_scale': 1})
        
        workbook.close()
        
        excel_data = buffer.getvalue()
        buffer.close()
        
        filename = f"{title.lower().replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.{self.get_file_extension()}"
        response = HttpResponse(excel_data, content_type=self.get_content_type())
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        
        return response 