from typing import List, Dict, Any
import io
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from django.http import HttpResponse
from django.utils.translation import gettext as _

from .report_generator import ReportGenerator


class PDFReportGenerator(ReportGenerator):
    
    
    def get_content_type(self) -> str:
        return 'application/pdf'
    
    def get_file_extension(self) -> str:
        return 'pdf'
    
    def generate_product_report(self, products: List[Dict[str, Any]], title: str = "Product Report") -> HttpResponse:
        
        buffer = io.BytesIO()
        
        
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            title=title,
            author="NEXO E-commerce",
            subject=_("Product Report"),
            keywords=["products", "report", "nexo"]
        )
        
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=16,
            textColor=colors.darkblue,
            spaceAfter=12,
            alignment=1  # Centrado
        )
        
        date_style = ParagraphStyle(
            'DateStyle',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.gray,
            alignment=1  # Centrado
        )
        
        
        elements = []
        
        
        elements.append(Paragraph(title, title_style))
        
        
        current_datetime = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        elements.append(Paragraph(_("Generated on: ") + current_datetime, date_style))
        elements.append(Spacer(1, 20))  
        
        
        table_data = [[
            _("Reference"), 
            _("Title"), 
            _("Description"), 
            _("Price (COP)"),
            _("Price (USD)")
        ]]
        
        for product in products:
            table_data.append([
                product.get('reference', ''),
                product.get('title', ''),
                product.get('description', '')[:50] + '...' if len(product.get('description', '')) > 50 else product.get('description', ''),
                f"{product.get('price', 0):,.0f}",
                f"${product.get('price_dolar', 0):.2f}"
            ])
        
        table = Table(table_data, repeatRows=1)
        
        
        table.setStyle(TableStyle([
            
            ('BACKGROUND', (0, 0), (-1, 0), colors.lightblue),  
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),  
            ('ALIGN', (0, 0), (-1, 0), 'CENTER'), 
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),  
            ('FONTSIZE', (0, 0), (-1, 0), 12),  
            
            
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'), 
            ('FONTSIZE', (0, 1), (-1, -1), 10),  
            ('ALIGN', (0, 1), (0, -1), 'CENTER'),  
            ('ALIGN', (3, 1), (4, -1), 'RIGHT'),  
            
            # Estilos de borde
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),  
            ('BOX', (0, 0), (-1, -1), 1, colors.black),  
            
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),  
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),  
        ]))
        
        
        elements.append(table)
        
        
        elements.append(Spacer(1, 20))
        footer_text = _("This report is automatically generated by NEXO E-commerce system.")
        elements.append(Paragraph(footer_text, styles['Italic']))
        
        doc.build(elements)
        
        pdf = buffer.getvalue()
        buffer.close()
        
        filename = f"{title.lower().replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}.{self.get_file_extension()}"
        response = HttpResponse(pdf, content_type=self.get_content_type())
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        
        return response 