# Generated by Django 5.1.7 on 2025-03-17 18:52

import apps.product.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('price_dolar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_popular', models.BooleanField()),
                ('is_new', models.BooleanField()),
                ('discontinued', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.product.models.product_image_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
