# Generated by Django 5.2.1 on 2025-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_description_alter_product_discontinued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_dolar',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
