# Generated by Django 5.2.1 on 2025-05-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('final', 'Final User')], default='final', max_length=10, verbose_name='User Type'),
        ),
    ]
